language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
  - npm run build:prod
deploy:
  provider: s3
  access_key_id: $AWSACCESSKEY
  secret_access_key: $AWSACCESSSECRET
  bucket: "smarttodo-react"
  region: "us-west-1"
  skip_cleanup: true
  local_dir: build